import test from "node:test"; import assert from "node:assert/strict"; import { mkdtempSync, readFileSync } from "node:fs"; import { tmpdir } from "node:os"; import { join } from "node:path";
import { DigestBuilder,serializeEmail } from "../src/auren-mail/digest.js"; import { CollectorRunner } from "../src/auren-mail/runner.js"; import { StateStore } from "../src/auren-mail/state.js"; import { MailGateway } from "../src/auren-mail/gmail-client.js"; import { MailMessage } from "../src/auren-mail/types.js";
const mail=(id:string,text="hello",account="a@gmail.com",unread=false):MailMessage=>({sourceAccount:account,id,threadId:`t-${id}`,internalDate:1700000000000,unread,from:"José <j@example.com>",to:account,cc:"",subject:"Unicode 📨",bodyText:text,bodyHtml:"<p>hello</p>",attachments:[{filename:"a.pdf",mimeType:"application/pdf",size:42,attachmentId:"ref"}],threadContext:[{id:"old",date:"yesterday",from:account,to:"j@example.com",bodyText:"prior reply"}]});
test("small digest contains raw fields, HTML, Unicode, attachments and context",()=>{const b=new DigestBuilder(4096);const m=mail("1");const p=b.build("d","2026-01-01T00:00:00Z",[m]);b.validate([m],p);assert.equal(p.length,1);for(const value of ["José","BODY_HTML","a.pdf","THREAD_CONTEXT","MESSAGE_ID: 1"])assert.match(p[0].body,new RegExp(value));});
test("size-based splitting preserves every message",()=>{const b=new DigestBuilder(1800);const ms=Array.from({length:8},(_,i)=>mail(String(i),"x".repeat(500)));const p=b.build("d","now",ms);assert.ok(p.length>1);b.validate(ms,p);assert.deepEqual(new Set(p.flatMap(x=>x.units)),new Set(ms.map(x=>`a@gmail.com:${x.id}`)));});
test("giant email is explicitly fragmented and exactly recoverable",()=>{const b=new DigestBuilder(1400),m=mail("giant","á😀".repeat(2000));const ps=b.build("d","now",[m]);b.validate([m],ps);const fragments=ps.flatMap(p=>p.body.match(/ENCODING: base64-utf8\n\n([^\n]+)/g)??[]).map(x=>x.split("\n\n")[1]);assert.ok(fragments.length>1);assert.equal(Buffer.from(fragments.join(""),"base64").toString(),serializeEmail(m,1));});
class Fake implements MailGateway { sent:number[]=[]; fail?:number; constructor(public data:Record<string,MailMessage[]>){} accounts(){return Object.keys(this.data)} async collect(a:string,after:number){return this.data[a].filter(m=>m.internalDate>after||m.unread)} async send(_a:string,_r:string,_s:string,_b:string,_d:string,p:number){if(this.fail===p)throw Error("network");this.sent.push(p)} }
const env=()=>{process.env.AUREN_DIGEST_RECIPIENT="central@example.com";process.env.AUREN_SENDER_ACCOUNT="a@gmail.com";process.env.AUREN_MAX_PART_BYTES="1500";process.env.AUREN_INITIAL_LOOKBACK_DAYS="99999";};
test("collector combines multiple accounts, new read and old unread",async()=>{env();const f=new Fake({"a@gmail.com":[mail("new-read","x","a@gmail.com")],"b@gmail.com":[mail("old-unread","x","b@gmail.com",true)]});const s=new StateStore(join(mkdtempSync(join(tmpdir(),"auren-")),"state.json"));const r=await new CollectorRunner(f,s,()=>new Date("2026-08-24T18:00:00Z")).run();assert.equal(r.emails,2);assert.ok(s.load().lastSuccessfulRun);assert.equal(s.load().pending,undefined);});
test("no new messages creates a valid empty manifest",async()=>{env();const f=new Fake({"a@gmail.com":[]}),s=new StateStore(join(mkdtempSync(join(tmpdir(),"auren-")),"state.json"));const r=await new CollectorRunner(f,s,()=>new Date("2026-08-24T18:00:00Z")).run();assert.equal(r.emails,0);assert.equal(r.parts,1);});
test("failed intermediate part keeps checkpoint and retry resumes",async()=>{env();const f=new Fake({"a@gmail.com":[mail("1","x".repeat(900)),mail("2","y".repeat(900))]});f.fail=2;const path=join(mkdtempSync(join(tmpdir(),"auren-")),"state.json"),s=new StateStore(path),clock=()=>new Date("2026-08-24T18:00:00Z"),runner=new CollectorRunner(f,s,clock);await assert.rejects(runner.run());assert.equal(s.load().lastSuccessfulRun,undefined);assert.deepEqual(s.load().pending?.sentParts,[1]);const total=s.load().pending!.parts.length;f.fail=undefined;await runner.run();assert.ok(s.load().lastSuccessfulRun);assert.deepEqual(f.sent,Array.from({length:total},(_,i)=>i+1));assert.doesNotMatch(readFileSync(path,"utf8"),/bodyText/);});
