import test from "node:test";
import assert from "node:assert/strict";
import { LocalAuthorizationService, LocalOAuthProvider, OAuthTokens, TokenRepository } from "../src/oauth-local-service.js";

class FakeProvider implements LocalOAuthProvider {
  exchanged?:{code:string;redirectUri:string;verifier:string}; tokens:OAuthTokens={accessToken:"access-secret",refreshToken:"refresh-secret"}; email="person@example.test"; fail=false;
  authorizationUrl(input:{redirectUri:string;state:string;challenge:string;scopes:string[]}){return `https://accounts.example.test/auth?redirect_uri=${encodeURIComponent(input.redirectUri)}&state=${input.state}&code_challenge=${input.challenge}&scope=${input.scopes.join("+")}`;}
  async exchangeCode(input:{code:string;redirectUri:string;verifier:string}){this.exchanged=input;if(this.fail)throw new Error("google response containing access-secret");return this.tokens;}
  async accountEmail(){if(this.fail)throw new Error("userinfo failed with refresh-secret");return this.email;}
}
class FakeStore implements TokenRepository { accounts=new Map<string,string>();get size(){return this.accounts.size}addAccount(email:string,token:string){this.accounts.set(email,token)}getTokensDataForExport(){return "encrypted-export"} }

test("generates a loopback OAuth URL with state, PKCE and required scopes",()=>{const provider=new FakeProvider(),service=new LocalAuthorizationService(provider,new FakeStore(),()=>{}),session=service.createSession("http://127.0.0.1:4321/oauth/callback");const url=new URL(session.url);assert.equal(url.searchParams.get("redirect_uri"),session.redirectUri);assert.equal(url.searchParams.get("state"),session.state);assert.ok(url.searchParams.get("code_challenge"));for(const scope of ["gmail.readonly","gmail.modify","gmail.send","userinfo.email"])assert.match(session.url,new RegExp(scope.replace(".","\\.")));assert.ok(session.verifier.length>40);});
test("exchanges code, obtains email and adds first account",async()=>{const provider=new FakeProvider(),store=new FakeStore(),service=new LocalAuthorizationService(provider,store,()=>{}),session=service.createSession("http://127.0.0.1:1/oauth/callback");const result=await service.complete(session,{code:"authorization-code",state:session.state});assert.equal(provider.exchanged?.code,"authorization-code");assert.equal(result.email,"person@example.test");assert.equal(result.tokensData,"encrypted-export");assert.equal(store.accounts.get(result.email),"refresh-secret");});
test("adds a second account while retaining the first",async()=>{const provider=new FakeProvider(),store=new FakeStore();store.addAccount("first@example.test","existing-token");provider.email="second@example.test";provider.tokens={refreshToken:"second-token"};const service=new LocalAuthorizationService(provider,store,()=>{}),session=service.createSession("http://127.0.0.1:2/oauth/callback");await service.complete(session,{code:"code",state:session.state});assert.deepEqual([...store.accounts.keys()],["first@example.test","second@example.test"]);});
test("rejects missing refresh token and malformed callback state",async()=>{const provider=new FakeProvider(),service=new LocalAuthorizationService(provider,new FakeStore(),()=>{}),session=service.createSession("http://127.0.0.1:3/oauth/callback");await assert.rejects(service.complete(session,{code:"code",state:"tampered"}),/state is invalid/);provider.tokens={accessToken:"access-only"};await assert.rejects(service.complete(session,{code:"code",state:session.state}),/refresh token/);});
test("rejects missing account email",async()=>{const provider=new FakeProvider();provider.email="";const service=new LocalAuthorizationService(provider,new FakeStore(),()=>{}),session=service.createSession("http://127.0.0.1:4/oauth/callback");await assert.rejects(service.complete(session,{code:"code",state:session.state}),/account email/);});
test("Google provider failures propagate without logging secrets",async()=>{const provider=new FakeProvider(),lines:string[]=[],service=new LocalAuthorizationService(provider,new FakeStore(),line=>lines.push(line)),session=service.createSession("http://127.0.0.1:5/oauth/callback");provider.fail=true;await assert.rejects(service.complete(session,{code:"code",state:session.state}),/access-secret/);assert.equal(lines.join("\n").includes("access-secret"),false);assert.equal(lines.join("\n").includes("refresh-secret"),false);});
